### ISSUE TITLE
Unknown target error since 1.1.32

### ISSUE THREAD

**Issue by SamRodri** [rust-lang/cc-rs#1261]
This no longer builds:

```toml
[dependencies]
zng-swgl = "0.3.0"
# cc = "=1.1.31" # version that works
```
```console
  --- stderr


  error occurred: unknown target `SWGLPP`
```

The build script file is here: [`build.rs`](https://github.com/zng-ui/zng-webrender/blob/main/swgl/build.rs). I'm not actually familiar with this code, as it is a fork of [webrender's `build.rs`](https://github.com/servo/webrender/blob/main/swgl/build.rs). The relevant code is probably:

```rust
let mut build = cc::Build::new();

// ..

// Use SWGLPP target to avoid pulling CFLAGS/CXXFLAGS.
build.target("SWGLPP");

// ..
```

Does the target method only expects Rust targets?
