### ISSUE TITLE
flag_if_supported("-lunwind") seems to always fail with ndk33 clang

### ISSUE THREAD

**Issue by plusls** [rust-lang/cc-rs#731]
Like #459

I compile A helloworld in windows with nightly-x86_64-pc-windows-msvc target  aarch64-linux-android, with 

```pwsh
cargo +nightly build -vv --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target aarch64-linux-android
```

it tell me that 

```
  = note: ld: error: unable to find library -lgcc
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

But I found a fix in https://github.com/rust-lang/rust/pull/85806, it check if compiler support lunwind, it will use system-llvm-libunwind.

https://github.com/rust-lang/rust/blob/1536ab1b383f21b38f8d49230a2aecc51daffa3d/library/unwind/build.rs#L19

And I change it to 

```rust
        let has_unwind = true;
```

It will compile and link success, so I think it's a bug that cause flag_if_supported("-lunwind") seems to always fail

And my cargo config:

```toml
[target.aarch64-linux-android]
linker = "C:\\Users\\plusls\\AppData\\Local\\Android\\Sdk\\ndk\\25.1.8937393\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android33-clang.cmd"
ar = "C:\\Users\\plusls\\AppData\\Local\\Android\\Sdk\\ndk\\25.1.8937393\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"



[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
```
