### ISSUE TITLE
How do I choose my own linker?

### ISSUE THREAD

**Issue by sirandreww** [rust-lang/cc-rs#919]
I'm working on a machine that has many linkers, I would like to choose which one is used for linking in `pub fn compile(&self, output: &str)`

**Comment by NobodyXu** [comment]
cc creates an archive, it does not link the object filed currently, so it doesn't use linker at all.

**Comment by Be-ing** [comment]
You can however use RUSTFLAGS with [`-C link-arg`](https://doc.rust-lang.org/rustc/codegen-options/index.html#link-arg). For example, to always use the mold linker, put this in ~/.cargo/config.toml

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=mold"
]
```
